### ISSUE TITLE
Integration with qa.debian.org

### ISSUE THREAD

**Issue by jasp00** [opencollab/clang.debian.net#4]
Since [debile.debian.net](http://debile.debian.net/) does not seem to be ready, could clang.debian.net be integrated into Debian PTS? A copy of pts.php that handles a package parameter, limits the SQL query, and adds basic HTML (link to the log) would be enough.

**Comment by sylvestre** [comment]
Good idea, do you want to give it a try?

**Comment by jasp00** [comment]
> do you want to give it a try?

My TODO list is really full; I would have made a pull request if I could. That said, I would love to give it try and I will if you do not mind a long delay.

**Comment by sylvestre** [comment]
Done, thanks again!
